import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { collection, query, orderBy, getDocs } from 'firebase/firestore';
import { db, auth } from '@/lib/firebase';
import { motion, AnimatePresence } from 'motion/react';
import { Users, Bot, MessageSquare } from 'lucide-react';

export default function MyTeamsScreen() {
  const { data: teams, isLoading } = useQuery({
    queryKey: ['saved_teams', auth.currentUser?.uid],
    queryFn: async () => {
      if (!auth.currentUser) return [];
      const q = query(
        collection(db, `users/${auth.currentUser.uid}/saved_teams`),
        orderBy('createdAt', 'desc')
      );
      const snap = await getDocs(q);
      return snap.docs.map(doc => ({ id: doc.id, ...doc.data() }));
    },
    enabled: !!auth.currentUser
  });

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      className="w-full h-full flex flex-col pt-4 px-4 overflow-y-auto pb-24 no-scrollbar"
    >
      <div className="mb-6 flex items-center gap-3">
        <div className="w-12 h-12 rounded-2xl bg-brand-blue/20 flex items-center justify-center border border-brand-blue/30">
          <Users className="w-6 h-6 text-brand-blue" />
        </div>
        <div>
          <h2 className="text-xl font-bold text-white">My AI Teams</h2>
          <p className="text-sm text-gray-400">Groups generated by the V-Link Oracle</p>
        </div>
      </div>

      {isLoading ? (
        <div className="flex-1 flex items-center justify-center">
          <div className="w-8 h-8 border-2 border-brand-blue border-t-transparent rounded-full animate-spin"></div>
        </div>
      ) : teams && teams.length > 0 ? (
        <div className="flex flex-col gap-4">
          {teams.map((team: any) => (
            <div key={team.id} className="glass-panel p-5 rounded-3xl border border-white/10 shadow-lg relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-32 h-32 bg-brand-blue/10 rounded-full blur-3xl -z-10 group-hover:bg-brand-blue/20 transition-colors" />
              
              <h3 className="text-lg font-bold text-white mb-4">{team.projectName || "AI Generated Team"}</h3>
              
              <div className="flex flex-col gap-3 mb-6">
                {team.members?.map((member: any, i: number) => (
                  <div key={i} className="flex items-center gap-3 bg-black/20 p-2 rounded-xl">
                    <div className="w-8 h-8 rounded-full bg-brand-dark overflow-hidden border border-white/10">
                      <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${member.name}`} alt="avatar" />
                    </div>
                    <div>
                      <p className="text-sm font-bold text-white">{member.name}</p>
                      <p className="text-[10px] text-brand-blue uppercase tracking-wider">{member.role}</p>
                    </div>
                  </div>
                ))}
              </div>
              
              <button className="w-full py-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl font-bold text-sm text-white flex items-center justify-center gap-2 transition-colors">
                <MessageSquare className="w-4 h-4" />
                Start Group Chat
              </button>
            </div>
          ))}
        </div>
      ) : (
        <div className="flex-1 flex flex-col items-center justify-center text-center px-6 mt-10">
          <div className="w-24 h-24 mb-6 relative">
            <div className="absolute inset-0 bg-brand-blue/20 rounded-full blur-xl" />
            <div className="w-full h-full glass-panel rounded-full flex items-center justify-center border border-white/10 relative z-10">
              <Bot className="w-10 h-10 text-brand-blue" />
            </div>
          </div>
          <h3 className="text-xl font-bold text-white mb-2">No teams yet!</h3>
          <p className="text-gray-400 text-sm leading-relaxed max-w-[250px]">
            Ask the V-Link Oracle to build a team for your next big project.
          </p>
        </div>
      )}
    </motion.div>
  );
}
